### ISSUE TITLE
Default math font aestethics

### ISSUE THREAD

**Issue by kklocker** [martstr/beamerthementnu#11]
**Personal opinion**: The default font looks terrible in math mode, and anyone who uses this slide template in a presentation should be aware of this. 

Reference pictures with different math fonts. Default (top), mathserif (bottom)
![before](https://user-images.githubusercontent.com/25065744/107029080-c01c9080-67ae-11eb-8e55-0e6181af131a.PNG)
![after](https://user-images.githubusercontent.com/25065744/107029083-c0b52700-67ae-11eb-8e19-130ee8258c02.PNG)

**Comment by VeroniMattia** [comment]
Any suggestions? If you give me a few alternatives, I will get in touch with the Communication Division and see if we can change them

**Comment by anates** [comment]
Maybe leave it open for the user to decide, by giving an option `[roman]` or similar?

**Comment by kklocker** [comment]
What happened to the linked pull request? I see that mathserif was added, but the pull request not merged? This issue can perhaps be closed

**Comment by VeroniMattia** [comment]
I changed the tex file before I saw your pull request, so I simply closed it. I'm doing to close this issue as well

**Comment by VeroniMattia** [comment]
<div class="js-discussion js-socket-channel ml-0 pl-0 ml-md-6 pl-md-3" data-channel="eyJjIjoibWFya2VkLWFzLXJlYWQ6MzkzMzY1NzIiLCJ0IjoxNjIxMzQ1NDcwfQ==--5829010cf538356915a5b087bc9e96c222e858e04603c0b1af220ae855ab87c5" data-channel-target="MDU6SXNzdWU4MDIwOTQ3ODY=" style="box-sizing: border-box; margin-left: 40px !important; padding-left: 16px !important; color: rgb(201, 209, 217); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box;"><div style="box-sizing: border-box;"><div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0MzE4NDg3NA==" style="box-sizing: border-box;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0MzE4NDg3NA==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg0MzE4NDg3NA==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issuecomment-843184874" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container editable-comment js-comment timeline-comment--caret reorderable-task-lists current-user" data-body-version="c7ace4f9ebe98f3efdd431e33f13174acc733b61a16af109f017ed7782bbb206" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border-color: var(--color-box-border-info); border-top-style: ; border-top-width: ; border-right-style: ; border-right-width: ; border-bottom-style: ; border-bottom-width: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists sortable="" style="box-sizing: border-box;">I changed the tex file before I saw your pull request, so I simply closed it. I'm closing this issue as well</task-lists></div><form class="js-comment-update" id="issuecomment-843184874-edit-form" action="https://github.com/martstr/beamerthementnu/issue_comments/843184874" accept-charset="UTF-8" method="post" style="box-sizing: border-box;"></form></div></div></div></div><div style="box-sizing: border-box;"><div class="js-timeline-marker js-socket-channel js-updatable-content" id="partial-timeline" data-channel="eyJjIjoiaXNzdWU6ODAyMDk0Nzg2IiwidCI6MTYyMTM0NTUxOH0=--2bb137133219626959deed7d6b02a272eae99536ab039be51da550eb0c95ecfa" data-url="/_render_node/MDU6SXNzdWU4MDIwOTQ3ODY=/issues/unread_timeline?variables%5BdeferCommitBadges%5D=false&amp;variables%5BdeferStatusCheckRollups%5D=false&amp;variables%5BdeferredCommentActions%5D=true&amp;variables%5BhasFocusedReviewComment%5D=false&amp;variables%5BhasFocusedReviewThread%5D=false&amp;variables%5BtimelinePageSize%5D=30&amp;variables%5BtimelineSince%5D=2021-05-18T13%3A45%3A16Z" data-last-modified="Tue, 18 May 2021 13:45:16 GMT" data-gid="MDU6SXNzdWU4MDIwOTQ3ODY=" style="box-sizing: border-box;"></div></div></div></div></div><span id="issue-comment-box" style="box-sizing: border-box; color: rgb(201, 209, 217); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></span><span style="color: rgb(201, 209, 217); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><div class="discussion-timeline-actions" style="box-sizing: border-box; background-color: var(--color-bg-canvas); border-top: 2px solid var(--color-border-primary); color: rgb(201, 209, 217); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="timeline-comment-wrapper timeline-new-comment js-comment-container js-targetable-element  ml-0 pl-0 ml-md-6 pl-md-3" id="issuecomment-new" style="box-sizing: border-box; margin-left: 40px !important; padding-left: 56px; position: relative; margin-top: 16px; margin-bottom: 0px;"><div class=" d-none d-md-block" style="box-sizing: border-box; display: block !important;"><br class="Apple-interchange-newline"></div></div></div>

**Comment by kklocker** [comment]
Soo this discussion should perhaps be opened again due to the rework in #17 ?

**Comment by kellertuer** [comment]
Feel free to do so. Do you have a preference, which math font to use?
Because I personally feel, that (a) slides should be sans serif (we use the university font anyways), and that the math font can be san serif then, too; that is fine with me.

**Comment by kklocker** [comment]
@kellertuer I agree that the default font should be sans serif, but not in math environments.
I imagine most people using Beamer is either in computer science or in other sciences, and frequently use math mode. I think it should be made easy to make good looking slides using these templates.

Creating a PR soon

**Comment by kellertuer** [comment]
Ok, it would be great if it can be done as an package option – or you add a page to the docs which package to load to change the font.
