### ISSUE TITLE
Upgrade repository: Documentation, Examples, name of the theme

### ISSUE THREAD

**Issue by kellertuer** [martstr/beamerthementnu#16]
I had a discussion today with @VeroniMattia and here is a short summary

* [x] We will only keep one variant, not multiple in subfolders
* [x] The variant will be the one with style files (resolved #14, now still in a subfolder).
* [x] The documentation should be extended to cover
  * [x] A good introduction to get started using the theme including examples – one for each language at least – presentations to get started directly and which files to copy where – thought for beginners both of latex beamer and latex in general
  * [x] A documentation of the available features for the intermediate user
  * [x] A  comprehensive technical documentation for the advanced user/developer
* [x] The documentation will be given as a presentation itself, since that can be used to illustrate usage of commands etc
* [x] We will move the URL of the repository (see #15), the old URL should forward to the new one for quite some time.
* [x] The style files will obtain a version number to track which version a user uses, but the name of the theme will just be `NTNU` without a year

**Comment by martstr** [comment]
Is there more I need to do to aid this process?

**Comment by kellertuer** [comment]
Thanks for moving the repo. With that I automatically gained owner rights, so from that side all is fine now.

For the remaining stuff above (rearrange the repo and stuff) you're help is of course welcome (best in branches and via PRs if we work on that together), but I know you are no longer at NTNU, so sure, no obligation to help, just if you are bored.
