### ISSUE TITLE
Title is too wide in title page if style=horizontal is used

### ISSUE THREAD

**Issue by tibnor** [martstr/beamerthementnu#6]
The title is shadowed by the NTNU name if style=horizontal is use. See minimal example under. This can be avoided by changing line 15 in beamerinnerthementnu2017.sty, such that width is adjusted depending on size.

\documentclass[screen, aspectratio=43]{beamer}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}

\usetheme[style=horizontal,language=en]{ntnu2017}

\usepackage[english]{babel}
\usepackage[style=numeric,backend=biber,natbib=false,sorting=none]{biblatex}

\title[Short title]{A very, very, very, very, very long title}
\author[O. Nordmann]{Ola Nordmann}
\institute[]{}
\date{}

\begin{document}

\begin{frame}
  \titlepage
\end{frame}

\end{document}

**Comment by martstr** [comment]
Thanks for your report, it is something that should be fixed.

If you need a fix straight away, use the smalltitle option to ntnu2017, i.e. 

\usetheme[style=horizontal,language=en, smalltitle]{ntnu2017}

Regarding your suggested fix. Do you have a concrete patch at hand, or some pseudocode? As far as I understood, you want to change the width specification in this line?

\begin{textblock*}{\paperwidth}(\titlex,\titley)

**Comment by kellertuer** [comment]
Is this still an active problem with the (new) 2020 theme or can this be closed, since it is too old anyways?

**Comment by kellertuer** [comment]
Since this is an old issue, I will close it for now. Feel free to reopen this, if the problem persists with the current reimplementation of the theme.
