### ISSUE TITLE
Problems with tikzexternalize

### ISSUE THREAD

**Issue by Hofsmo** [martstr/beamerthementnu#7]
Hi, when I use tikzexternalize I get the following text over the tikz generated figures "includegraphics optimized away because it does not contribute to exported pdf". However, if I disable optimize using   \tikzset{external/optimize=false} I get the NTNU logo over all my pictures. Any ides on what could be wrong?

**Comment by martstr** [comment]
Har du et minimalt eksempel?

Den ons. 7. nov. 2018, 13:56 skrev Sigurd Hofsmo Jakobsen <
notifications@github.com>:

**Comment by Hofsmo** [comment]
Slik no har eg eitt "minimalt" eksempel. Då eg berre laga ein liten tikz figur så fekk eg ikkje problemet. Eg prøvde difor å legga til eitt pgfplot og då fekk eg problemet. 
Eksempelet ligg her https://github.com/Hofsmo/minimalt-eksempel

**Comment by Hofsmo** [comment]
Hei,
Forslaget i denne tråden https://tex.stackexchange.com/questions/66804/unexpected-output-using-tikz-textpos fiksa same problemet i ein artikkelmal. Eg ser at det vert nemnd av nokon at dette kan fiksa problemet for beamermaler også.

**Comment by kellertuer** [comment]
Is this still an active problem with the (new) 2020 theme or can this be closed, since it is too old anyways?

**Comment by kellertuer** [comment]
Since this is an old issue, I will close it for now. Feel free to reopen this, if the problem persists with the current reimplementation of the theme.
