### ISSUE TITLE
Using columns in 169 vertical format breaks left margin

### ISSUE THREAD

**Issue by giampierosalvi** [martstr/beamerthementnu#9]
Hi,
I noticed that the left margin is correct when using 169 aspect ratio and vertical style as long as you have no columns defined. If you use columns, then the left margin overlaps with the vertical blue bar. Is there an easy fix for this? At the end I add an example file that shows the problem.

Thank you!
Giampiero

\documentclass[screen, aspectratio=169]{beamer}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}

% Use the NTNU-temaet for beamer 
% \usetheme[style=ntnu|simple|vertical|horizontal, 
%     language=bm|nn|en, 
%     smalltitle, 
%     city=all|trondheim|alesund|gjovik]{ntnu2017}
\usetheme[style=vertical,language=en]{ntnu2017}

\usepackage[english]{babel}
\usepackage[style=numeric,backend=biber,natbib=false,sorting=none]{biblatex}

\begin{document}

\begin{frame}
  \frametitle{Failing margin on left columns}
  \begin{columns}
    \begin{column}{0.5\textwidth}
      \begin{itemize}
      \item one
      \item two
      \item three
      \end{itemize}
    \end{column}
    \begin{column}{0.5\textwidth}
      \begin{itemize}
      \item one
      \item two
      \item three
      \end{itemize}
    \end{column}
    \end{columns}
\end{frame}

\end{document}

**Comment by giampierosalvi** [comment]
Apparently this is because defining two columns with width 0.5\textwidth goes over the actual width of the text (because a gap of space is added between the columns). A solution is to reduce the width, for example to 0.425\textwidth. I never notice this before, because I never used a style with a left graphic item in the background. More information [here](https://tex.stackexchange.com/questions/366419/same-multi-columns-width-with-different-margins-in-beamer/366422#366422).

**Comment by kellertuer** [comment]
Is this still an active problem with the (new) 2020 theme or can this be closed, since it is too old anyways?

**Comment by kellertuer** [comment]
Since this is an old issue, I will close it for now. Feel free to reopen this, if the problem persists with the current reimplementation of the theme.
